## Dynamic configuration
version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.7
    networks:
      - proxy_network
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      - "8088:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - './traefik/traefik.yaml:/etc/traefik/traefik.yml'
      # - './traefik/config.yaml:/etc/traefik/config.yml'
    restart: always
    environment:
      - TRAEFIK_API=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_INSECURE=true
      # - TRAEFIK_ENTRYPOINTS_HTTP=true
      - TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
      # - TRAEFIK_GLOBAL_CHECKNEWVERSION=false
      # - TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE=false
      - TRAEFIK_LOG=true
      # - TRAEFIK_LOG_LEVEL=INFO
      # - TRAEFIK_PROVIDERS_DOCKER=true
      # - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      # - TRAEFIK_PROVIDERS_DOCKER_NETWORK=${COMPOSE_PROJECT_NAME:-narc-services}_proxy_net
      # - TRAEFIK_PROVIDERS_FILE_FILENAME=/etc/traefik/traefik.providers.file.toml
      # - TRAEFIK_PROVIDERS_FILE_WATCH=true
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks: 
      - proxy_network
    volumes:
      - nginx
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.nginx.rule=(Host(`narclab.com`) && Path(`/vnc`)) || Host(`vnc.narclab.com`)"
      - "traefik.http.routers.nginx.entrypoints=web"
  #     # Middleware
    

  arango:
    container_name: arango-db
    image: arangodb/arangodb:3.9.1
    restart: always
    depends_on: 
      - traefik
    networks:
      - proxy_network   # make accessible by HTTP
    volumes:
      - arangodb:/data
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    # ports:
    #   - 8529:8529
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.arango.rule=(Host(`narclab.com`) && Path(`/data`)) || Host(`data.narclab.com`)"
      - "traefik.http.routers.arango.entrypoints=web"
  #     # Middleware
  #     # - "traefik.http.middlewares.arango.headers.stsincludesubdomains=true"
  #     # - "traefik.http.middlewares.arango.headers.stsseconds=315360000"
  #     # - "traefik.http.middlewares.arango_headers.headers.forcestsheader=true"
  #     # # Service
  #     # - "traefik.http.services.guac.loadbalancer.server.port=8080"


  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: always
    depends_on:
      - traefik
    networks:
      - guac_network
      # - proxy_network

  guac_db:
    container_name: guac_db
    image: postgres:10.4-alpine
    restart: always
    depends_on:
      - traefik
    # environment:
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_USER=${MYSQL_USERNAME}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_DATABASE=guacamole
    volumes:
      # - "./guacamole:/docker-entrypoint-initdb.d"
      - guacdb:/var/lib/postgresql/data
    networks:
      - guac_network
      # - proxy_network

  remote_desktop:
    container_name: guac_client
    image: guacozy/guacozy-server
    restart: always
    # ports: 
      # - 8081:8080
    links:  
      - guacd:guacd
      - guac_db:guac_db
    depends_on:
      - guac_db
      - guacd
      - traefik
    volumes:
      # - "./guacamole/server.xml:/usr/local/tomcat/conf/server.xml"
      # - "./guacamole:/guac_home"
      # - ".guacamole/ssl:/ssl/"
      - ./certs:/ssl
      - ./guacamole/ldap_config.py:/app/guacozy_server/ldap_config.py
    environment:
      # - GUACAMOLE_HOME=/guac_home
      # # - MYSQL_HOSTNAME=guac_db
      # - MYSQL_DATABASE=guacamole
      # - MYSQL_USER=${MYSQL_USERNAME}
      - DJANGO_SECRET_KEY=${MYSQL_PASSWORD}
      # - FIELD_ENCRYPTION_KEY=someplaceholdinghashsomeplaceholdinghashsomeplaceholdinghashsomeplaceholdinghashsomeplaceholdinghashsomeplaceholdinghashsomeplaceholdinghash
      - DJANGO_DB_URL=postgres://postgres@guac_db:5432/postgres
      - DJANGO_ALLOWED_HOSTS=remote.narclab.com
      - GUACD_HOSTNAME=guacd
      # - GUACD_PORT=4822
    networks:
      - backend_network
      - proxy_network
    labels:
      - "traefik.enable=true"
      # - "traefik.port=80"
      # - "traefik.frontend.rule=remote.narclab.com"
      # HTTP
      - "traefik.http.routers.guacamole.rule=(Host(`narclab.com`) && Path(`/remote`)) || Host(`remote.narclab.com`)"
      - "traefik.http.routers.guacamole.entrypoints=web"
      # - "traefik.http.routers.guacamole.service=guacBalance"
      # - "traefik.http.routers.guacamole.middlewares=guacPrefix"
      # # Middleware
      # - "traefik.http.middlewares.guac_headers.headers.stsincludesubdomains=true"
      # - "traefik.http.middlewares.guac_headers.headers.stsseconds=315360000"
      # - "traefik.http.middlewares.guac_headers.headers.forcestsheader=true"
      # - "traefik.http.middlewares.guacPrefix.addprefix.prefix=/guacamole"
      # # Service
      # - "traefik.http.services.guacBalance.loadBalancer.server.port=8080"

  lean_db:
      container_name: lean_db
      image: tiredofit/mariadb
      restart: always
      depends_on:
        - traefik
      environment:
      #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #   - MYSQL_USER=${MYSQL_USERNAME}
      #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #   - MYSQL_DATABASE=leantime
        # for tiredofit's package w/ mariadb
        - ROOT_PASS=password
        - DB_NAME=leantime
        - DB_USER=leantime
        - DB_PASS=leantime
      # command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
      volumes:
        # - ./leantime/schema.sql:/var/lib/mysql/schema.sql:ro
        # ./leantime:/config
        # - leandb:/var/lib/mysql
        - lean_mariadb:/var/lib/mysql

      networks:
        - leantime_network
        # - backend_network
        # - proxy_network

  leantime: 
    container_name: leantime_client
    image: tiredofit/leantime
    environment:
      - VIRTUAL_HOST=remote.narclab.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=remote.narclab.com
      - LETSENCRYPT_EMAIL=${EMAIL}
      - CONTAINER_NAME=leantime_client
      - DB_HOST=lean_db
      - DB_NAME=leantime
      - DB_USER=leantime
      - DB_PASS=leantime
      - SITE_URL=remote.narclab.com
      - SITE_NAME=NARemote
      - ADMIN_EMAIL=${EMAIL}
      - ADMIN_PASS=admin
      - ADMIN_LAST_NAME=Administrator
      - COMPANY_NAME=mssm
      # - LEAN_DB_HOST=lean_db
      # - LEAN_DB_USER=admin
      # - LEAN_DB_PASSWORD=${DEFAULT_ROOT_PASSWORD}
      # - LEAN_DB_DATABASE=leantime
      # - LEAN_APP_URL=http://projects.narclab.com
    # ports:
    #   - "80:80"
    networks:
      - leantime_network
      - proxy_network
    depends_on:
      - lean_db
      - traefik
    links:
      - lean_db:lean_db
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.leantime.rule=(Host(`narclab.com`) && Path(`/projects`)) || Host(`projects.narclab.com`)"
      - "traefik.http.routers.leantime.entrypoints=web"
      # Middleware
      # - "traefik.http.middlewares.leantime_headers.headers.stsincludesubdomains=true"
      # - "traefik.http.middlewares.leantime_headers.headers.stsseconds=315360000"
      # - "traefik.http.middlewares.leantime_headers.headers.forcestsheader=true"
      # # Service
      - "traefik.http.services.leantime.loadBalancer.server.port=8080"

networks:
  proxy_network:
    external: true
  backend_network:
    external: true
  guac_network:
    external: true
  leantime_network:
    external: true

volumes:
  arangodb:
    external: true
  leandb: {}
  lean_mariadb: {}
  guacdb: {}
  ssl:
  staticfiles:
